[package]
name = "ds-ext"
version = "0.1.0"
authors = ["code@tinychain.net"]
edition = "2021"
license = "Apache-2.0"
description = "Extensions to standard Rust data structures which provide additional capabilities"
repository = "https://github.com/haydnv/freqache"
readme = "README.md"

categories = ["data-structures"]
keywords = ["ordered", "set", "map", "custom", "order"]

[dependencies]
derive_more = { version = "0.99", features=["display"] }
get-size = "0.1"
get-size-derive = "0.1"
regex = "1.7"
safecast = { path = "../safecast" }

[dev-dependencies]
rand = "0.8"
